when:
  - event: [push, tag]
    branch: main

steps:
  - name: build
    image: codeberg.org/woodpecker-plugins/node-pm
    commands:
      - npm ci
      - npm run build
      # deploy to codeberg pages

depends_on:
  - build
